/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MEMBRE (void);
GtkWidget* create_COACH (void);
GtkWidget* create_ADMINISTRATION (void);
GtkWidget* create_CONNECTION (void);
